name: App Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: InfraConfig
        uses: tu-usuario/actions-repo/InfraConfig@main

      - name: Build
        run: echo "Building"

      - name: Deploy
        run: echo "Deploying"

      - name: Test
        uses: tu-usuario/actions-repo/Tests@main
        with:
          param1: 'test-param1'
          param2: 'test-param2'